// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwmbwypjqspqwxzmaxxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bWJ3eXBqcXNwcXd4em1heHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjE5NjIsImV4cCI6MjA1NTc5Nzk2Mn0.aZPNK5xb6XPYisH5Hx1U356lX5zvypS-iFcpjdwLq2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);